name: CI

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.number }}

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    secrets: inherit
